### PR TITLE
Added support for proxy module

### LINKED ISSUE #75: Proxy module
How do I use the proxy module with this module ? Do I need to manually set my STRAPI_URL env to the same as the nuxt project? this seems highly unconvienient. Is there a way for this module to expose the $http modules proxy and prefix options ?

Thanks! Love the module btw

### PR DESCRIPTION
**Pull request by Blemming**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Exposes the prefix and proxy options of the $http module to be able to use the @nuxtjs/proxy module and fixes #75 

## Checklist:

- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)
No tests where added since the proxy module is an opt-in option

### CODE REVIEW

**Comment by Atinux** [comment]
Thank you for the PR, what is the purpose of using a proxy for Strapi since it does support CORS?

**Comment by Blemming** [comment]
It supports CORS but not everyone will have it turned on, also I much prefer the workflow of using proxy's, no surprises at deployment. It is also recommended in the $http module documentation to turn on this option exactly for these reasons.

Also sorry for the messy commits, this is my first PR 😁

**Comment by Atinux** [comment]
I will have to try but I think a simple example should be enough by setting the proxy option and STRAPI_URL to /api

**Comment by Blemming** [comment]
The http module uses Ky ,Ky requires an absolute url unless the prefix option is set.

**Comment by tylerforesthauser** [comment]
Hey guys! Just checking in to see if there was any progress on this as this is a very useful feature for me, as well. I'm currently using this PR in my project without issue but I'd love to see it included in an official release.

Thanks!

**Comment by Atinux** [comment]
Closing in favour of #87 

Please see https://strapi.nuxtjs.org/proxy :)

**Pull request closed without merging**
